import random

_PROFILES = [
    {"device_model": "Samsung Galaxy S24 Ultra", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy S24+", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy S24", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy S23 Ultra", "system_version": "Android 14", "app_version": "10.11.0", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy S23+", "system_version": "Android 14", "app_version": "10.11.0", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy S23", "system_version": "Android 14", "app_version": "10.11.0", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy S22 Ultra", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy S22+", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy S22", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy S21 Ultra", "system_version": "Android 12", "app_version": "9.6.7", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy S21+", "system_version": "Android 12", "app_version": "9.6.7", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy S21", "system_version": "Android 12", "app_version": "9.6.7", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy Z Fold5", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy Z Fold4", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy Z Flip5", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy A55", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy A54", "system_version": "Android 13", "app_version": "10.11.0", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy A53", "system_version": "Android 13", "app_version": "10.8.3", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy A52s", "system_version": "Android 12", "app_version": "9.5.4", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy A35", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy A34", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy A33", "system_version": "Android 12", "app_version": "9.7.3", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy M54", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy M53", "system_version": "Android 12", "app_version": "9.6.7", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy M34", "system_version": "Android 13", "app_version": "10.7.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Samsung Galaxy M33", "system_version": "Android 12", "app_version": "9.5.4", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi 14 Pro", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi 14", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi 13 Ultra", "system_version": "Android 13", "app_version": "10.11.0", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi 13 Pro", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi 13", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi 12 Pro", "system_version": "Android 12", "app_version": "9.8.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi 12", "system_version": "Android 12", "app_version": "9.7.3", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi Redmi Note 13 Pro+", "system_version": "Android 13", "app_version": "10.11.0", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi Redmi Note 13 Pro", "system_version": "Android 13", "app_version": "10.11.0", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi Redmi Note 13", "system_version": "Android 13", "app_version": "10.11.0", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi Redmi Note 12 Pro+", "system_version": "Android 13", "app_version": "10.8.3", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi Redmi Note 12 Pro", "system_version": "Android 13", "app_version": "10.8.3", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi Redmi Note 12", "system_version": "Android 13", "app_version": "10.8.3", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi Redmi Note 11 Pro", "system_version": "Android 12", "app_version": "9.6.7", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi Redmi Note 11", "system_version": "Android 11", "app_version": "9.4.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi Redmi 13C", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi Redmi 12C", "system_version": "Android 12", "app_version": "9.7.3", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi Redmi 10C", "system_version": "Android 11", "app_version": "9.4.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Xiaomi Redmi 10", "system_version": "Android 11", "app_version": "9.3.2", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "POCO F5 Pro", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "POCO F5", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "POCO X6 Pro", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "POCO X6", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "POCO X5 Pro", "system_version": "Android 13", "app_version": "10.7.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "POCO X5", "system_version": "Android 12", "app_version": "10.5.0", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "POCO M6 Pro", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "POCO M5", "system_version": "Android 12", "app_version": "9.7.3", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Realme 12 Pro+", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Realme 12 Pro", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Realme 11 Pro+", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Realme 11 Pro", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Realme 10 Pro+", "system_version": "Android 13", "app_version": "10.8.3", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Realme 10 Pro", "system_version": "Android 13", "app_version": "10.8.3", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Realme GT5 Pro", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Realme GT3", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Realme GT 2 Pro", "system_version": "Android 12", "app_version": "9.7.3", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "OnePlus 12", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "OnePlus 11", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "OnePlus 10 Pro", "system_version": "Android 13", "app_version": "10.7.5", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "OnePlus 10T", "system_version": "Android 13", "app_version": "10.7.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "OnePlus 9 Pro", "system_version": "Android 12", "app_version": "9.6.7", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "OnePlus 9", "system_version": "Android 12", "app_version": "9.6.7", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "iPhone 15 Pro Max", "system_version": "17.4", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "iPhone 15 Pro", "system_version": "17.4", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "iPhone 15 Plus", "system_version": "17.4", "app_version": "10.14.5", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "iPhone 15", "system_version": "17.4", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "iPhone 14 Pro Max", "system_version": "17.2", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "iPhone 14 Pro", "system_version": "17.2", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "iPhone 14 Plus", "system_version": "17.0", "app_version": "10.6.1", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "iPhone 14", "system_version": "17.0", "app_version": "10.6.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "iPhone 13 Pro Max", "system_version": "16.6", "app_version": "10.4.2", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "iPhone 13 Pro", "system_version": "16.6", "app_version": "10.4.2", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "iPhone 13 mini", "system_version": "16.6", "app_version": "10.4.2", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "iPhone 13", "system_version": "16.6", "app_version": "10.6.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "iPhone 12 Pro Max", "system_version": "16.1", "app_version": "9.9.2", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "iPhone 12 Pro", "system_version": "16.1", "app_version": "9.9.2", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "iPhone 12 mini", "system_version": "16.1", "app_version": "9.9.2", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "iPhone 12", "system_version": "16.1", "app_version": "9.9.2", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Pixel 8 Pro", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "Pixel 8a", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "Pixel 8", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "Pixel 7 Pro", "system_version": "Android 13", "app_version": "10.7.5", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "Pixel 7a", "system_version": "Android 13", "app_version": "10.7.5", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "Pixel 7", "system_version": "Android 13", "app_version": "10.7.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Pixel 6a", "system_version": "Android 13", "app_version": "10.5.0", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "Pixel 6 Pro", "system_version": "Android 13", "app_version": "10.5.0", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "Huawei P60 Pro", "system_version": "Android 12", "app_version": "9.8.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Huawei Mate 50 Pro", "system_version": "Android 12", "app_version": "9.8.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Huawei Nova 11 Pro", "system_version": "Android 12", "app_version": "9.7.3", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Huawei Nova 11", "system_version": "Android 12", "app_version": "9.7.3", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "OPPO Find X6 Pro", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "OPPO Reno11 Pro", "system_version": "Android 14", "app_version": "10.14.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "OPPO Reno10 Pro+", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "vivo V29 Pro", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "vivo X90 Pro", "system_version": "Android 13", "app_version": "10.7.5", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Nothing Phone (2)", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "Nothing Phone (1)", "system_version": "Android 13", "app_version": "10.7.5", "lang_code": "en", "system_lang_code": "en-US"},
    {"device_model": "Motorola Edge 40 Pro", "system_version": "Android 13", "app_version": "10.9.1", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Motorola Edge 40", "system_version": "Android 13", "app_version": "10.8.3", "lang_code": "ru", "system_lang_code": "en-US"},
    {"device_model": "Motorola Moto G84", "system_version": "Android 13", "app_version": "10.7.5", "lang_code": "ru", "system_lang_code": "en-US"},
]


_PYROGRAM_KEYS = {"device_model", "system_version", "app_version", "lang_code"}


def random_device() -> dict:
    profile = random.choice(_PROFILES)
    return {k: v for k, v in profile.items() if k in _PYROGRAM_KEYS}
